### ISSUE TITLE
如何解决：[Error] 出现错误: <class 'UnboundLocalError'>

### ISSUE THREAD

**Issue by happyokay** [RimoOvO/Mastodon-to-Twitter-Sync#4]
你好，
我的 api 应该都设置好了，发了一条嘟文，然后卡在这里无限循环了，怎么办？

[opc@wiki Mastodon-to-Twitter-Sync]$ python mtSync.py
[2024-01-21 11:46:37] [Init] 同步检查间隔： 60 秒
[2024-01-21 11:46:37] [Init] 同步到日志文件： 是
[2024-01-21 11:46:37] [Init] 最大重试次数/等待时间(秒)： 13 / 1800.0
[2024-01-21 11:46:38] [Init] 验证 Mastodon API 授权成功，用户名： hx
[2024-01-21 11:46:39] [Init] 验证 Twitter API 授权成功，用户名： happy xiao 🧑‍💻 aa.ee

[2024-01-21 11:46:39] [Check] 子线程：开始监控新嘟文...
[2024-01-21 11:47:39] [Check] 发现新嘟文：111793774042393464 已加入待同步列表
[2024-01-21 11:47:40] [Error] 出现错误: <class 'UnboundLocalError'>
1
[2024-01-21 11:47:40] [Error] 尝试重试...
[2024-01-21 11:47:41] [Error] 出现错误: <class 'UnboundLocalError'>
2
[2024-01-21 11:47:41] [Error] 尝试次数：#2，等待 3 秒后下一次重试...
[2024-01-21 11:47:44] [Error] 出现错误: <class 'UnboundLocalError'>
3
[2024-01-21 11:47:44] [Error] 尝试次数：#3，等待 6 秒后下一次重试...
[2024-01-21 11:47:51] [Error] 出现错误: <class 'UnboundLocalError'>
4
[2024-01-21 11:47:51] [Error] 尝试次数：#4，等待 12 秒后下一次重试...
^CException ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1315, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1077, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1093, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by happyokay** [comment]
<img width="821" alt="SCR-20240206-sflm" src="https://github.com/RimoOvO/Mastodon-to-Twitter-Sync/assets/7081538/f1e4e97d-3181-48ef-8786-5dcf931ace01">
 
换了好几台小鸡，都这样

**Comment by suliang01** [comment]
我也是一样的情况

**Comment by XiaoMouz** [comment]
加todo了，没看到不好意思（
明天晚上查

可以麻烦提供一下 python 版本以及联邦站点（或者站点是什么平台的）

**Comment by happyokay** [comment]
没事：）
我用的 phthon 3，站点是 c.im，不过最近切到 Mastodon.social 了

试了你的项目很多次，在不同的vps上都没成功，最后开通了IFTTT的Pro+ 用来同步🤦

谢谢

From: XiaoMouz ***@***.***>
Date: Monday, February 26, 2024 at 01:32
To: RimoOvO/Mastodon-to-Twitter-Sync ***@***.***>
Cc: happy ***@***.***>, Author ***@***.***>
Subject: Re: [RimoOvO/Mastodon-to-Twitter-Sync] 如何解决：[Error] 出现错误: <class 'UnboundLocalError'> (Issue #4)

加todo了，没看到不好意思（
明天晚上查

可以麻烦提供一下 python 版本以及联邦站点（或者站点是什么平台的）

**Comment by Nakolu** [comment]
> 加todo了，没看到不好意思（ 明天晚上查
> 
> 可以麻烦提供一下 python 版本以及联邦站点（或者站点是什么平台的）

python3.9  版本出现该问题，在 debian12 和 win10 平台运行都会出现 <class 'UnboundLocalError'> 报错

注释掉如下代码后，程序正常运行
```
  # # 检查嘟文结尾是否以 “#no_sync” tag 结尾
    # if toot_text.endswith('#no_sync'):
    #     tprint(colored('[Check] 嘟文结尾包含不同步标签 #no_sync ，跳过...','green'))
    #     save_synced_toots(toot_id)
    #     return 0
```

**Comment by RimoOvO** [comment]
fixed at [aceaf08](https://github.com/RimoOvO/Mastodon-to-Twitter-Sync/commit/aceaf0881bcb27ed0387e415c2c2ed2394b0e794)
